version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    networks:
      - traefik
    volumes:
      - jenkins_home:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.foo.org`)"
      - "traefik.http.routers.jenkins.entrypoints"

networks:
  traefik:
     external: true

volumes:
  jenkins_home: