
version: '3'

services:
  openldap:
    container_name: openldap
    image: osixia/openldap
    ports: 
      - "389:389"
      - "636:636"
    command: [--copy-service,  --loglevel, debug]
    environment:
      - LDAP_ORGANISATION="foo"
      - LDAP_DOMAIN="foo.org"
      - LDAP_ADMIN_PASSWORD="ldap123"
    # volumes:
    #   - /Users/xie/Workspaces/data/openldap/database:/var/lib/ldap
    #   - /Users/xie/Workspaces/data/openldap/config:/etc/ldap/slapd.d
    restart: always

  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin
    ports: 
      - "10004:80"
    restart: always
    environment:
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    links:
      - openldap
    depends_on:
      - openldap