
version: '3'

services:
  openldap:
    image: osixia/openldap
    ports: 
      - "389:389"
    networks:
      - openldap
    environment:
      - LDAP_ORGANISATION=zhiantech
      - LDAP_DOMAIN=zhiantech.com
      - LDAP_ADMIN_PASSWORD=567534
    volumes:
      - database:/var/lib/ldap
      - config:/etc/ldap/slapd.d
    restart: always

  phpldapadmin:
    image: osixia/phpldapadmin
    ports: 
      - "10004:80"
    networks:
      - traefik
      - openldap
    restart: always
    environment:
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpldapadmin.rule=Host(`pda.foo.org`)"
      - "traefik.http.routers.phpldapadmin.entrypoints"
    depends_on:
      - openldap

networks:
  openldap:
    driver: bridge
  traefik:
     external: true

volumes:
  database:
  config: