apiVersion: v1
kind: Namespace
metadata:
  name: kube-ops
  labels:
    name: kube-ops
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce
  namespace: kube-ops
  labels:
    name: gitlab-ce
spec:
  selector:
    app: gitlab-ce
  type: NodePort 
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: ssh
    port: 22
    targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-ce
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      app: gitlab-ce
  template:
    metadata:
      labels:
        app: gitlab-ce
    spec:
      containers:
      - name: gitlab-ce
        image: gitlab/gitlab-ce:latest
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: GITLAB_TIMEZONE
          value: Beijing

        - name: GITLAB_ROOT_PASSWORD
          value: gitlab123
        - name: GITLAB_ROOT_EMAIL
          value: root@foo.org

        - name: GITLAB_HOST
          value: "gitlab.foo.org"
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

        volumeMounts:
          - mountPath: /var/opt/gitlab
            name: data
          - mountPath: /var/log/gitlab
            name: logs
          - mountPath: /etc/gitlab
            name: config
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22

      volumes:
        - name: data
          hostPath:
            path: ~/Workspaces/data/gitlab/data
        - name: logs
          hostPath:
            path: ~/Workspaces/data/gitlab/logs
        - name: config
          hostPath:
            path: ~/Workspaces/data/gitlab/config
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: kube-ops
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:10.10-alpine
        env:
          - name: POSTGRES_PASSWORD
            value: passw0rd
          - name: POSTGRES_USER
            value: gitlab
          - name: POSTGRES_DB
            value: gitlab_production
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kube-ops
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0.14-alpine
        ports:
        - containerPort: 6379
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitlab-ce
  namespace: kube-ops
  labels:
    type: ingress
    app: gitlab-ce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gitlab.foo.org
    http:
      paths:
      - backend:
          serviceName: gitlab-ce
          servicePort: 80