apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitlab-ce
  namespace: kube-ops
spec:
  rules:
  - host: gitlab.foo.org
    http: 
      paths:
      - path: /
        backend:
          serviceName: gitlab-ce
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-prometheus-server
  namespace: kube-ops
spec:
  rules:
  - host: prometheus.foo.org
    http: 
      paths:
      - path: /
        backend:
          serviceName: prometheus-prometheus-server
          servicePort: 80
