version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    networks:
      - traefik
      - default
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


# 先创建外部网卡
# docker network create traefik
networks:
  traefik:
     external: true
